### PR TITLE
Release version restriction for jax

### PR DESCRIPTION
**Pull request by ericmjl**
This was causing issues in installation from PyPI.

### CODE REVIEW

**Comment by ericmjl** [comment]
@ElArkk I vote we just merge, and then cut a release so that the PyPI installation releases the <0.2.0 restriction. If you're ok with that, please do the honors! Otherwise, we can fix what you think needs fixing.

**Comment by ElArkk** [comment]
@ericmjl I just re-ran the tests, I think codecov complaining is a bug that sometimes happens, where it can't merge the two coverage reports. Gonna hit merge in any case after this :)

**Comment by ericmjl** [comment]
Oh right, forgot about the fast and slow tests.

**Comment by ElArkk** [comment]
Seems like that was indeed the issue 😄  merging!

**Pull request merged**
